### ISSUE TITLE
[Question]: Demo ran failed in ROS2 Humble 

### ISSUE THREAD

**Issue by EndlessLoops** [Interbotix/interbotix_ros_turrets#5]
### Question

I tested three demo in the simulation, but all of them failed to run.Did I miss installing a package?

**Terminal output:**
```
$ python3 turret_mixed_profile_control.py 
[INFO] [1730685437.354623507] [interbotix_robot_manipulation]: Initialized InterbotixRobotNode!
[INFO] [1730685437.419791908] [interbotix_robot_manipulation]: 
	Robot Name: pxxls
	Robot Model: pxxls
[INFO] [1730685437.420147354] [interbotix_robot_manipulation]: Initialized InterbotixRobotXSCore!
Traceback (most recent call last):
  File "/home/ubuntu/ros2_interbotix_ws/src/interbotix_ros_turrets/interbotix_ros_xsturrets/interbotix_xsturret_control/demos/turret_mixed_profile_control.py", line 113, in <module>
    main()
  File "/home/ubuntu/ros2_interbotix_ws/src/interbotix_ros_turrets/interbotix_ros_xsturrets/interbotix_xsturret_control/demos/turret_mixed_profile_control.py", line 58, in main
    robot = InterbotixTurretXS(
  File "/home/ubuntu/ros2_interbotix_ws/install/interbotix_xs_modules/lib/python3.10/site-packages/interbotix_xs_modules/xs_robot/turret.py", line 107, in __init__
    self.turret = InterbotixTurretXSInterface(
  File "/home/ubuntu/ros2_interbotix_ws/install/interbotix_xs_modules/lib/python3.10/site-packages/interbotix_xs_modules/xs_robot/turret.py", line 185, in __init__
    rclpy.spin_until_future_complete(self.core, self.future_group_info)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 248, in spin_until_future_complete
    executor.spin_until_future_complete(future, timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 288, in spin_until_future_complete
    self.spin_once_until_future_complete(future, timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 716, in spin_once_until_future_complete
    self.spin_once(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 705, in spin_once
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 691, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 492, in _wait_for_ready_callbacks
    subscriptions.extend(filter(self.can_execute, node.subscriptions))
AttributeError: 'InterbotixRobotXSCore' object has no attribute 'subscriptions'

```

### Robot Model

pxxls

### Operating System

Other (Describe in "Anything Else")

### ROS Version

Other (Describe in "Anything Else")

**Comment by ncnynl** [comment]
The humble version code of interbotix_xs_toolbox does not match, the modified version is as shown in the link:

`https://gitee.com/ncnynl/interbotix_ros_toolboxes/blob/humble/interbotix_xs_toolbox/interbotix_xs_modules/interbotix_xs_modules/xs_robot/turret.py
`

Some places need self.core.robot_node to replace self.core

**Comment by asaj** [comment]
I ran into this as well, and had to make similar changes across other files and packages. I'll see if I can open some PRs in the next couple days.
